
ARG RUST_VERSION=1.96.0

FROM rust:${RUST_VERSION}-slim-bullseye AS build
ARG APP_NAME
WORKDIR /app

RUN --mount=type=bind,source=src,target=src \
    --mount=type=bind,source=Cargo.toml,target=Cargo.toml \
    --mount=type=bind,source=Cargo.lock,target=Cargo.lock \
    --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
    <<EOF
set -e

cargo build --release --bin $APP_NAME
cp ./target/release/$APP_NAME /bin/server
EOF

COPY setup_pki.sh ./
COPY deploy_reverse_firewall_3nodes.sh ./
COPY docker/docker-entrypoint.sh ./

FROM debian:bullseye-slim AS final

RUN set -ex; \
    apt-get update -y ; \
    apt-get install -y --no-install-recommends \
      openssl openssh-client

WORKDIR /app

COPY --from=build app/setup_pki.sh ./setup_pki.sh
COPY --from=build app/deploy_reverse_firewall_3nodes.sh ./deploy_reverse_firewall_3nodes.sh
COPY --from=build app/docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x docker-entrypoint.sh
RUN chmod +x deploy_reverse_firewall_3nodes.sh
RUN chmod +x setup_pki.sh

ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/home/appuser" \
    --shell "/bin/bash" \   
    --uid "${UID}" \
    appuser && \
    mkdir -p /home/appuser/.ssh && \
    chmod 700 /home/appuser/.ssh && \
    chown -R appuser:appuser /home/appuser
USER appuser

COPY --from=build /bin/server /bin/

ARG APP_NAME
ENV APP_NAME=$APP_NAME
ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["/bin/server"]